In [1]:
#load data from excel format
import pandas as pd
import numpy as np
df = pd.read_excel(open('default of credit card clients.xls','rb'),sheetname='Data') 
df.head(10)

,ID,X1,X2,X3,X4,X5,X6,X7,X8,X9,...,X15,X16,X17,X18,X19,X20,X21,X22,X23,Y
0,1,20000,2,2,1,24,2,2,-1,-1,...,0,0,0,0,689,0,0,0,0,1
1,2,120000,2,2,2,26,-1,2,0,0,...,3272,3455,3261,0,1000,1000,1000,0,2000,1
2,3,90000,2,2,2,34,0,0,0,0,...,14331,14948,15549,1518,1500,1000,1000,1000,5000,0
3,4,50000,2,2,1,37,0,0,0,0,...,28314,28959,29547,2000,2019,1200,1100,1069,1000,0
4,5,50000,1,2,1,57,-1,0,-1,0,...,20940,19146,19131,2000,36681,10000,9000,689,679,0
5,6,50000,1,1,2,37,0,0,0,0,...,19394,19619,20024,2500,1815,657,1000,1000,800,0
6,7,500000,1,1,2,29,0,0,0,0,...,542653,483003,473944,55000,40000,38000,20239,13750,13770,0
7,8,100000,2,2,2,23,0,-1,-1,0,...,221,-159,567,380,601,0,581,1687,1542,0
8,9,140000,2,3,1,28,0,0,2,0,...,12211,11793,3719,3329,0,432,1000,1000,1000,0
9,10,20000,1,3,2,35,-2,-2,-2,-2,...,0,13007,13912,0,0,0,13007,1122,0,0

In [2]:
# select feature list
feature_list = ['X6', 
'X7', 
'X8',
'X9',
'X10' ,
'X11' ,
'X1'  ,
'X18' ,
'X19' ,
'X21' ,
'X20' ,
'X22' ,
'X23' ,
'X2'  ,
'X3'  ,
'X4'  ,
'X12' ,
'X13' ,
'X14' ]

In [3]:
# using selected feature to get new features 
X = df[feature_list]
y = df.Y

In [4]:
from sklearn.cross_validation import train_test_split
from sklearn.metrics import f1_score
from sklearn import metrics
from sklearn import preprocessing


from sklearn.naive_bayes import MultinomialNB


l = []
for i in range(10):
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)
    min_max_scaler = preprocessing.MinMaxScaler()
    x_train_scaled = min_max_scaler.fit_transform(X_train[X_train.columns[0:19]])
    x_test_scaled = min_max_scaler.fit_transform(X_test[X_test.columns[0:19]])
    X_train_robust = pd.DataFrame(x_train_scaled)
    X_test_robust = pd.DataFrame(x_test_scaled)
  
    
    nb = MultinomialNB()
    nb.fit(X_train_robust, y_train)
    y_pred_class = nb.predict(X_test_robust)

    l.append(f1_score(y_test, y_pred_class, average='micro'))
    print('Round{} : '.format(i))
    print(nb.score(X_train_robust,y_train))
    print(nb.score(X_test_robust,y_test))
    print(f1_score(y_test, y_pred_class, average='micro'))
    print(metrics.classification_report(y_test, y_pred_class))
    print('#################################')
print(sum(l)/10)

/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/sklearn/cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)
/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/sklearn/metrics/classification.py:1113: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)

Round0 :
0.7795
0.776
0.776
             precision    recall  f1-score   support

          0       0.78      1.00      0.87      4656
          1       0.00      0.00      0.00      1344

avg / total       0.60      0.78      0.68      6000

#################################
Round1 :
0.778166666667
0.781333333333
0.781333333333
             precision    recall  f1-score   support

          0       0.78      1.00      0.88      4688
          1       0.00      0.00      0.00      1312

avg / total       0.61      0.78      0.69      6000

#################################
Round2 :
0.780833333333
0.770666666667
0.770666666667
             precision    recall  f1-score   support

          0       0.77      1.00      0.87      4624
          1       0.00      0.00      0.00      1376

avg / total       0.59      0.77      0.67      6000

#################################
Round3 :
0.78075
0.771
0.771
             precision    recall  f1-score   support

          0       0.77      1.00      0.87      4626
          1       0.00      0.00      0.00      1374

avg / total       0.59      0.77      0.67      6000

#################################
Round4 :
0.77875
0.779
0.779
             precision    recall  f1-score   support

          0       0.78      1.00      0.88      4674
          1       0.00      0.00      0.00      1326

avg / total       0.61      0.78      0.68      6000

#################################
Round5 :
0.778541666667
0.779833333333
0.779833333333
             precision    recall  f1-score   support

          0       0.78      1.00      0.88      4679
          1       0.00      0.00      0.00      1321

avg / total       0.61      0.78      0.68      6000

#################################
Round6 :
0.779875
0.7745
0.7745
             precision    recall  f1-score   support

          0       0.77      1.00      0.87      4647
          1       0.00      0.00      0.00      1353

avg / total       0.60      0.77      0.68      6000

#################################
Round7 :
0.777916666667
0.782333333333
0.782333333333
             precision    recall  f1-score   support

          0       0.78      1.00      0.88      4694
          1       0.00      0.00      0.00      1306

avg / total       0.61      0.78      0.69      6000

#################################
Round8 :
0.780291666667
0.772833333333
0.772833333333
             precision    recall  f1-score   support

          0       0.77      1.00      0.87      4637
          1       0.00      0.00      0.00      1363

avg / total       0.60      0.77      0.67      6000

#################################
Round9 :
0.78025
0.773
0.773
             precision    recall  f1-score   support

          0       0.77      1.00      0.87      4638
          1       0.00      0.00      0.00      1362

avg / total       0.60      0.77      0.67      6000

#################################
0.77605